# Generated by Django 4.1 on 2024-06-22 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('meaning', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
