# Generated by Django 4.1 on 2024-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteword',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
