# Generated by Django 4.1 on 2024-06-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_favorite_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteword",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
