# Generated by Django 5.0.6 on 2024-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrenchWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonetic", models.CharField(blank=True, max_length=255, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("function", models.CharField(blank=True, max_length=255, null=True)),
                ("word", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "words_fr",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="GermanWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonetic", models.CharField(blank=True, max_length=255, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("function", models.CharField(blank=True, max_length=255, null=True)),
                ("word", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "words_ge",
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="words",
            options={"managed": True},
        ),
    ]
